import 'series.dart';

final List<Series> initialSeries = [
      Series(
        title: 'Breaking Bad',
        trama: 'Walter White, un professore di chimica delle superiori che si trasforma in un produttore di metanfetamine dopo aver scoperto di avere un cancro ai polmoni.',
        genere: 'Drammatico, Crime',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
      ),
      Series(
        title: 'Stranger Things',
        trama: 'Quando un ragazzo scompare, la sua città natale si ritrova al centro di un mistero che coinvolge esperimenti governativi segreti, forze soprannaturali terrificanti e una ragazzina molto strana.',
        genere: 'Sci-Fi, Horror',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
      ),
      Series(
        title: 'The Mandalorian',
        trama: 'Le avventure di un cacciatore di taglie mandaloriano nei confini esterni della galassia, lontano dall\'autorità della Nuova Repubblica.',
        genere: 'Sci-Fi, Avventura',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
      ),
      Series(
        title: 'House of the Dragon',
        trama: 'La saga della Casa Targaryen ambientata 200 anni prima degli eventi de Il Trono di Spade.',
        genere: 'Fantasy, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
      ),
      Series(
        title: 'Wednesday',
        trama: 'Segue Wednesday Addams come studentessa alla Nevermore Academy, dove tenta di padroneggiare le sue abilità psichiche emergenti.',
        genere: 'Commedia, Horror',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
      ),
      Series(
        title: 'The Boys',
        trama: 'Un gruppo di vigilanti si propone di abbattere dei supereroi corrotti che abusano delle loro superpotenze.',
        genere: 'Azione, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg',
      ),
      Series(
        title: 'Game of Thrones',
        trama: 'Nove famiglie nobili combattono per il controllo dei Sette Regni di Westeros.',
        genere: 'Fantasy, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
      ),
      Series(
        title: 'La Casa di Carta',
        trama: 'Un gruppo di rapinatori organizza la più grande rapina della storia alla Zecca di Stato spagnola.',
        genere: 'Crime, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYmVjODRhNDAtZDU1Ni00ODc3LWIzNjMtODM5MTEwODJmMDExXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Dark',
        trama: 'Quattro famiglie sono coinvolte in un mistero che abbraccia diverse generazioni e viaggi nel tempo.',
        genere: 'Sci-Fi, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
      ),
      Series(
        title: 'The Witcher',
        trama: 'Il cacciatore di mostri Geralt di Rivia lotta per trovare il suo posto in un mondo dove le persone spesso si dimostrano più malvagie delle bestie.',
        genere: 'Fantasy, Avventura',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/zrPpUlehQaBf8YX2NrVrKK8IEpf.jpg',
      ),
      Series(
        title: 'Peaky Blinders',
        trama: 'Una famiglia criminale britannica guida una gang a Birmingham nel periodo post-bellico.',
        genere: 'Crime, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
      ),
      Series(
        title: 'Lost',
        trama: 'I sopravvissuti di un incidente aereo si ritrovano su un\'isola misteriosa piena di segreti.',
        genere: 'Drammatico, Mistero',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZmZhY2ViYzYtMTQ0NS00NDcyLWIxZTYtMGUyODE0NDA0NmNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Sherlock',
        trama: 'Una rivisitazione moderna delle avventure di Sherlock Holmes e del Dr. Watson.',
        genere: 'Crime, Mistero',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNTQzNGZjNDEtOTMwYi00MzFjLWE2ZTYtYzYxYzMwMjZkZDc5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Friends',
        trama: 'Le vicende di sei amici che vivono a Manhattan.',
        genere: 'Commedia, Romantico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg',
      ),
      Series(
        title: 'How I Met Your Mother',
        trama: 'Ted racconta ai suoi figli la storia di come ha conosciuto la loro madre.',
        genere: 'Commedia, Romantico',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNjg1MDQ5MjQ2N15BMl5BanBnXkFtZTYwNjI5NjA3._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'The Office',
        trama: 'La vita quotidiana degli impiegati di un ufficio di Scranton, Pennsylvania.',
        genere: 'Commedia',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
      ),
      Series(
        title: 'The Crown',
        trama: 'La storia della regina Elisabetta II e della famiglia reale britannica.',
        genere: 'Drammatico, Storico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNjU2NzA5MzgyM15BMl5BanBnXkFtZTgwNDAwOTUxMDI@._V1_.jpg',
      ),
      Series(
        title: 'Vikings',
        trama: 'Le avventure del leggendario vichingo Ragnar Lothbrok.',
        genere: 'Storico, Azione',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg',
      ),
      Series(
        title: 'The Big Bang Theory',
        trama: 'Le avventure di un gruppo di amici nerd e le loro relazioni.',
        genere: 'Commedia',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg',
      ),
      Series(
        title: 'Better Call Saul',
        trama: 'La storia dell\'avvocato Jimmy McGill prima di diventare Saul Goodman.',
        genere: 'Crime, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Dexter',
        trama: 'Un ematologo della polizia di Miami conduce una doppia vita come serial killer.',
        genere: 'Crime, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://image.tmdb.org/t/p/w500/58H6Ctze1nnpS0s9vPmAAzPcipR.jpg',
      ),
      Series(
        title: 'Narcos',
        trama: 'La storia vera della crescita e della caduta del cartello della droga di Pablo Escobar.',
        genere: 'Crime, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/rTmal9fDbwh5F0waol2hq35U4ah.jpg',
      ),
      Series(
        title: 'Black Mirror',
        trama: 'Una serie antologica che esplora un futuro distopico e le conseguenze della tecnologia.',
        genere: 'Sci-Fi, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BODcxMWI2NDMtYTc3NC00OTZjLWFmNmUtM2NmY2I1ODkxYzczXkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg',
      ),
      Series(
        title: 'The Walking Dead',
        trama: 'Un gruppo di sopravvissuti cerca di restare in vita in un mondo invaso dagli zombie.',
        genere: 'Horror, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://image.tmdb.org/t/p/w500/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg',
      ),
      Series(
        title: 'Prison Break',
        trama: 'Un uomo si fa incarcerare di proposito per aiutare il fratello a evadere dal carcere.',
        genere: 'Azione, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_.jpg',
      ),
      Series(
        title: 'Lucifer',
        trama: 'Lucifero, annoiato e infelice come Signore degli Inferi, si trasferisce a Los Angeles.',
        genere: 'Crime, Fantasy',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg',
      ),
      Series(
        title: 'Arrow',
        trama: 'Dopo essere stato disperso su un\'isola, Oliver Queen torna a casa per combattere il crimine.',
        genere: 'Azione, Avventura',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg',
      ),
      Series(
        title: 'The Flash',
        trama: 'Barry Allen acquisisce il potere della super velocità e diventa il supereroe Flash.',
        genere: 'Azione, Sci-Fi',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg',
      ),
      Series(
        title: 'Supernatural',
        trama: 'Due fratelli cacciano demoni, fantasmi e altre creature soprannaturali.',
        genere: 'Horror, Fantasy',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://image.tmdb.org/t/p/w500/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg',
      ),
      Series(
        title: 'Suits',
        trama: 'Un giovane brillante senza laurea in legge viene assunto da un importante studio legale di New York.',
        genere: 'Drammatico, Commedia',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/vQiryp6LioFxQThywxbC6TuoDjy.jpg',
      ),
      Series(
        title: 'Brooklyn Nine-Nine',
        trama: 'Le avventure di una squadra di detective del 99° distretto di polizia di Brooklyn.',
        genere: 'Commedia, Crime',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg',
      ),
      Series(
        title: 'Grey\'s Anatomy',
        trama: 'Le vite personali e professionali di un gruppo di medici a Seattle.',
        genere: 'Drammatico, Romantico',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://image.tmdb.org/t/p/w500/daSFbrt8QCXV2hSwB0hqYjbj681.jpg',
      ),
      Series(
        title: 'The 100',
        trama: 'Un gruppo di giovani viene inviato sulla Terra per vedere se è abitabile dopo un\'apocalisse nucleare.',
        genere: 'Sci-Fi, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg',
      ),
      Series(
        title: 'Sense8',
        trama: 'Otto sconosciuti da diverse parti del mondo scoprono di essere mentalmente e emotivamente collegati.',
        genere: 'Sci-Fi, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjA4MTEyMzcwMl5BMl5BanBnXkFtZTgwMTIwODczNTM@._V1_.jpg',
      ),
      Series(
        title: 'The Umbrella Academy',
        trama: 'Una famiglia disfunzionale di supereroi adottivi si riunisce per risolvere il mistero della morte del padre.',
        genere: 'Azione, Sci-Fi',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/scZlQQYnDVlnpxFTxaIv2g0BWnL.jpg',
      ),
      Series(
        title: 'Elite',
        trama: 'Tre ragazzi di umili origini vengono ammessi in una scuola esclusiva spagnola.',
        genere: 'Drammatico, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg',
      ),
      Series(
        title: 'The Good Doctor',
        trama: 'Un giovane chirurgo autistico con la sindrome del savant lavora in un prestigioso ospedale.',
        genere: 'Drammatico, Medico',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://image.tmdb.org/t/p/w500/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg',
      ),
      Series(
        title: 'Modern Family',
        trama: 'Tre famiglie diverse ma imparentate affrontano le sfide della vita quotidiana.',
        genere: 'Commedia',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYzFlOWFjNzQtODViNC00NzgzLThhZmItZTc1N2VlZDgwODUwXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Gomorra',
        trama: 'La storia della camorra napoletana e delle sue lotte di potere.',
        genere: 'Crime, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYWUwYmYwNmItMTRiMy00ZDBhLWE3OTUtMDdmYjA1Mzc2M2IwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'The Handmaid\'s Tale',
        trama: 'In una società distopica, le donne fertili sono costrette a servire come ancelle.',
        genere: 'Drammatico, Sci-Fi',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://image.tmdb.org/t/p/w500/oIkxqt6ug5zT5ZSUUyc1Iqopf02.jpg',
      ),
      Series(
        title: 'This Is Us',
        trama: 'Le vite di una famiglia americana attraverso diverse generazioni.',
        genere: 'Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMzNlYzgyZDktZDVkYy00MDVkLTkyYmQtYjM4Y2E0Njc1NDE1XkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'The Simpsons',
        trama: 'Le avventure della famiglia Simpson nella città di Springfield.',
        genere: 'Animazione, Commedia',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNTU2OWE0YWYtMjRlMS00NTUwLWJmZWUtODFhNzJiMGJlMzI3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Rick and Morty',
        trama: 'Le avventure di uno scienziato pazzo e di suo nipote attraverso universi paralleli.',
        genere: 'Animazione, Sci-Fi',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',
      ),
      Series(
        title: 'The Mentalist',
        trama: 'Un consulente con straordinarie capacità di osservazione aiuta la polizia a risolvere crimini.',
        genere: 'Crime, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTQ5OTgzOTczM15BMl5BanBnXkFtZTcwMDM2OTY4MQ@@._V1_.jpg',
      ),
      Series(
        title: 'Homeland',
        trama: 'Un\'agente della CIA sospetta che un marine americano sia stato convertito dal nemico.',
        genere: 'Thriller, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjAwNTRmODktZDk5Ny00ZjMwLWFhMDUtOTdlOWNhNDMyZmNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'House',
        trama: 'Un medico geniale ma anticonformista risolve casi clinici complessi.',
        genere: 'Drammatico, Medico',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://image.tmdb.org/t/p/w500/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg',
      ),
      Series(
        title: 'Mr. Robot',
        trama: 'Un giovane programmatore viene reclutato da un misterioso anarchico per distruggere una multinazionale.',
        genere: 'Thriller, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTg4NTBiZDAtZTc0YS00NzZlLTg4Y2ItNGQ3M2ZlMDM5MWQzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'The Originals',
        trama: 'La famiglia di vampiri originali torna a New Orleans per riprendere il controllo della città.',
        genere: 'Fantasy, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZDJkYjg3MDItMjhiMi00NjhjLThlM2EtNzUxNzcyNDJjN2ZhXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'The Blacklist',
        trama: 'Un criminale ricercato si consegna all\'FBI offrendo di aiutare a catturare altri criminali.',
        genere: 'Crime, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://image.tmdb.org/t/p/w500/htJzeRcYI2ewMm4PTrg98UMXShe.jpg',
      ),
      Series(
        title: 'The Good Place',
        trama: 'Una donna si ritrova nell\'aldilà e cerca di diventare una persona migliore.',
        genere: 'Commedia, Fantasy',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNjI3ZGRhNDYtNDFjOS00OGFlLTg4NTEtYjZjYTViY2ZiMzBkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Alessandro Borghese: Quattro Ristoranti',
        trama: 'Quattro ristoratori si sfidano per scoprire chi ha il miglior ristorante in una determinata categoria.',
        genere: 'Reality, Cucina',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://artworks.thetvdb.com/banners/series/306595/posters/5eb053e1c1bab.jpg',
      ),
      Series(
        title: 'The Last of Us',
        trama: 'In un mondo post-apocalittico, un uomo e una giovane ragazza devono attraversare gli Stati Uniti per sopravvivere.',
        genere: 'Drammatico, Azione',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Ted Lasso',
        trama: 'Un allenatore di football americano viene assunto per allenare una squadra di calcio inglese, nonostante non abbia esperienza nel calcio.',
        genere: 'Commedia, Sport',
        stato: 'Da guardare',
        piattaforma: 'Apple TV+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMDE5OTkxM2EtMDM1ZC00MDRlLWI5MTgtNjNkMzdlYzY0NzQ2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Invincible',
        trama: 'Un adolescente scopre di avere poteri sovrumani e cerca di seguire le orme del padre, il supereroe più potente della Terra.',
        genere: 'Animazione, Azione',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNDQ4YTUwZDMtNmUwOC00MmI5LTljMjMtMTE5MzdjMjc4NWFkXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Cucine da Incubo - Italia',
        trama: 'Il famoso chef Antonino Cannavacciuolo visita ristoranti in difficoltà in Italia per aiutarli a risollevarsi.',
        genere: 'Reality, Cucina',
        stato: 'Da guardare',
        piattaforma: 'Sky',
        imageUrl: 'https://images.justwatch.com/poster/307603062/s718/cucine-da-incubo.jpg',
      ),
      Series(
        title: 'Formula 1: Drive to Survive',
        trama: 'Una serie che offre uno sguardo dietro le quinte del mondo della Formula 1, seguendo le squadre e i piloti durante la stagione.',
        genere: 'Documentario, Sport',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMmZjOTcxNjMtOThjZi00ODE5LTkxYzktNjk5ZGRjYWFhYTRiXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Boris',
        trama: 'Una serie comica che segue le disavventure di un gruppo di cineasti italiani durante la produzione di una fiction televisiva.',
        genere: 'Commedia',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOGUwMzI0YTItNGUyOS00NDRiLWI1NGEtMWIzNTNiMmEwOWIwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Sex Education',
        trama: 'Un adolescente insicuro e la sua amica decidono di aprire una clinica di consulenza sessuale nella loro scuola.',
        genere: 'Commedia, Drammatico',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTE0MjQ1NDU3OV5BMl5BanBnXkFtZTgwNTI4MTgwNzM@._V1_.jpg',
      ),
      Series(
        title: 'Death Note',
        trama: 'Un giovane studente trova un quaderno che gli permette di uccidere chiunque scriva il nome su di esso.',
        genere: 'Animazione, Thriller',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Attacco dei Giganti',
        trama: 'In un mondo dove l\'umanità è sull\'orlo dell\'estinzione a causa di giganti che divorano gli esseri umani, un gruppo di giovani soldati combatte per la sopravvivenza.',
        genere: 'Animazione, Azione',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Code Geass: Lelouch of the Rebellion',
        trama: 'Un giovane principe esiliato ottiene il potere di controllare le menti degli altri e decide di usarlo per rovesciare l\'Impero Britannico.',
        genere: 'Animazione, Azione',
        stato: 'Da guardare',
        piattaforma: 'Netflix',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNTk4MWYwNmUtODFjNC00NWJhLWExNGYtMGU4YmRlNzEwOTY1XkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'Daredevil',
        trama: 'Un avvocato cieco di giorno diventa un vigilante mascherato di notte, combattendo il crimine a Hell\'s Kitchen.',
        genere: 'Azione, Crime',
        stato: 'Da guardare',
        piattaforma: 'Disney+',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BODcwOTg2MDE3NF5BMl5BanBnXkFtZTgwNTUyNTY1NjM@._V1_FMjpg_UX1000_.jpg',
      ),
      Series(
        title: 'Top Gear',
        trama: 'Un programma di intrattenimento automobilistico che presenta recensioni di auto, sfide e avventure in tutto il mondo.',
        genere: 'Documentario, Automobilismo',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNTJlYmZjNDAtYjA2YS00YjAyLWI4NmYtYjFhNmM5MDEyMWJmXkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'The Grand Tour',
        trama: 'Tre ex presentatori di Top Gear viaggiano per il mondo in auto, presentando sfide e avventure.',
        genere: 'Documentario, Automobilismo',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOGQ1M2Y4ZjMtNWRiNS00YTUzLTkxMzEtZjgzYmZjMGVlMzY5XkEyXkFqcGc@._V1_.jpg',
      ),
      Series(
        title: 'The Office',
        trama: 'Una serie comica che segue la vita quotidiana degli impiegati di un ufficio di Scranton, Pennsylvania.',
        genere: 'Commedia',
        stato: 'Da guardare',
        piattaforma: 'Prime Video',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZjQwYzBlYzUtZjhhOS00ZDQ0LWE0NzAtYTk4MjgzZTNkZWEzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      )
    ];